### ISSUE TITLE
Add summaries to historygenerator.py

### ISSUE THREAD

**Issue by Loughlinstown** [weatherstorm/Sofaskin-CW9009#11]
Thanks very much for your skin and previous help J.
I see that https://github.com/brewster76/fuzzy-archer/blob/master/bin/user/historygenerator.py file now includes a summary column (see http://meteolavall.no-ip.org/weewx/history.html for a sample page which includes it).
I really like your implementation of the NOAA monthly summaries and am not keen to lose that style of presentation.

I've tried comparing the code between your modified version of brewster76's  historygenerator linked above, and this latest one and whilst a lot of it is identical I'm afraid it's beyond my abilities to correctly add the summary column functionality from one to the other.
Any chance you might review at some point and add to your modified version?

My own summary page is here if you are interested - https://www.loughlinstown.ie/records.html

Many thanks,

Muireadach.

**Comment by weatherstorm** [comment]
Thanks for using my skin. I didn't know he updated his script with a sum column. I believe merged my updated code base for the historygenerator.py before he did this update but I will look into it.

**Comment by weatherstorm** [comment]
I have the updated to the new version of historygeneratoy.py with my minor changes and its working on my server. If it remains stable, I will upload the code within a few days. 

http://cw9009.x10host.com/summary.html

**Comment by Loughlinstown** [comment]
Nice work!, thank you so much!

**Comment by Loughlinstown** [comment]
Just installed the new file, works great!, thanks again.

**Comment by weatherstorm** [comment]
Thanks for letting me know about the update.
