### ISSUE TITLE
Update Skin to Python 3 and WeeWx 4.0.0.

### ISSUE THREAD

**Issue by weatherstorm** [weatherstorm/Sofaskin-CW9009#14]
It looks like WeeWx 4 is stable so it's time to convert the skin to the latest version. Only significant change I can see thus far is with the historygenerator.py script. The author has update the code base so will include the changes soon.

**Comment by weatherstorm** [comment]
Skin is stable with the weewx and python. I also found a few bugs. Will post the updates soon

**Comment by harmlessdrudge** [comment]
Just tried out this skin (with WeeWX 4.3 on Ubuntu 20.04 with Python3, on a Pi3). At a glance it seems mostly ok apart from: not generating a week.html file, or NOAA reports; favicon also not in an images folder (which should be copied on start). My current modified Sofaskin (original) version has templates directory with a header.html.tmpl file but lacks an error directory.

Looking forward to seeing updated version.

**Comment by harmlessdrudge** [comment]
Seems the problem with week.html.tmpl is in the Yesterday section; page works if it's removed. If included:

```
Jan 27 23:00:33 ubuntu python3[2566]: weewx[2566] ERROR weewx.cheetahgenerator: **** Reason: '<' not supported between instances of 'AggTypeBinder' and 'int'
Jan 27 23:00:33 ubuntu python3[2566]: weewx[2566] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Jan 27 23:00:33 ubuntu python3[2566]: weewx[2566] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 323, in generate
Jan 27 23:00:33 ubuntu python3[2566]: weewx[2566] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Jan 27 23:00:33 ubuntu python3[2566]: weewx[2566] ERROR weewx.cheetahgenerator: ****    File "_etc_weewx_skins_Sofaskin_CW9009_week_html_tmpl.py", line 643, in respond
Jan 27 23:00:33 ubuntu python3[2566]: weewx[2566] ERROR weewx.cheetahgenerator: ****  TypeError: '<' not supported between instances of 'AggTypeBinder' and 'int'
```

**Comment by weatherstorm** [comment]
Yes. I have been working on that bug as well as a few other. Python changed how they handle < or > symbols. I have a fix for it that I will upload soon. I have it working on my site.

**Comment by weatherstorm** [comment]
Issues have been fixed.
