### ISSUE TITLE
Replace text.php with Javascript and Ajax

### ISSUE THREAD

**Issue by weatherstorm** [weatherstorm/Sofaskin-CW9009#15]
Should replace the text.php with xml code which will be easier to maintain. I have a basic framework written but more testing needs to be done.

**Comment by harmlessdrudge** [comment]
Sounds good, but it would be great to see a version working w Python 3 and then this as an enhancement (if that's not impatient :-)

**Comment by harmlessdrudge** [comment]
Great to see the update. Got a note about WeeWX 4.4 shortly after!

**Comment by weatherstorm** [comment]
Code for the new Jquery and Ajax version working. Still testing it out.

https://centuryfarmweather.com/textxml.html?report=NOAA/NOAA-2019-01.txt
https://centuryfarmweather.com/textxml.html?report=NOAA/NOAA-2019.txt
