### ISSUE TITLE
Lightning distance

### ISSUE THREAD

**Issue by harmlessdrudge** [weatherstorm/Sofaskin-CW9009#20]
Hello and Season's Greetings. In advance of the new year I've acquired a lightning detector and made some mods to my web site which borrows from yours (acknowledged). Thanks for your "lightning bug" fix. However, I am seeing

Average Strike Distance | $day.lightning_avg_distance.avg

instead of a value reported for the average distance (expected value zero atm). I haven't yet had time to look into it but am wondering if you have a variable declared in weewx.conf or what I'm missing here.

**Comment by weatherstorm** [comment]
Happy Holidays! So I am using the driver mapped parameters for a WeatherFlow Tempest Station which might be different from your variable map used by your weather station. I would check your station documentation to see what lightning data is sent from your station. It's likely that the variables one station uses are different from another.
