### ISSUE TITLE
Cheetahgenerator fails to generate index.html if web_url is not defined

### ISSUE THREAD

**Issue by KurtJacobson** [weatherstorm/Sofaskin-CW9009#3]
Traceback:
```
cheetahgenerator: **** Ignoring template /home/wx/weewx/skins/Sofaskin/index.html.tmpl
cheetahgenerator: **** Reason: cannot find 'web_url' while searching for 'Extras.web_url'
```
At first glance it does not look like `Extras.web_url` is absolutely required for generating `index.html`, so should probably add a `#if $Extras.has_key('web_url')` were needed.

**Comment by weatherstorm** [comment]
Thank you. I fixed them.
