### ISSUE TITLE
Use `preg_split` instead of `split` in text.php.tmpl

### ISSUE THREAD

**Issue by KurtJacobson** [weatherstorm/Sofaskin-CW9009#5]
`text.php.tmpl` uses the PHP function `split` which was deprecated in PHP 5.3.0, and completely removed in PHP 7.0.0. This causes servers running PHP 7.0.0 or later to completely fail to load the Monthly Reports page. Since the current stable is 7.2.1, and most up-to-date servers will probably be running at least 7.0.14, users are likely to encounter this problem. `split` should be replaced with `preg_split`.

**Comment by weatherstorm** [comment]
Thank you. In order for the preg_split to work correctly the pattern has to be updated to "/[\s-.]/"

**Comment by KurtJacobson** [comment]
Great thank you! I did not notice that the regex syntax had changed with the new extension.
