### ISSUE TITLE
Change top header color

### ISSUE THREAD

**Issue by Blisk** [weatherstorm/Sofaskin-CW9009#7]
How to change that blue/green top color?

**Comment by weatherstorm** [comment]
Sorry for the delay in my response. You can control the background color of the header and footer in the main.css file. For example, the head background color is here: 

header {
  **background: #05c2d8;**
  width: 100%;
  color: #fff;
  font-weight: 300;
  padding: 1em 0 0 0; }

You will see the same thing in the footer section as well.
