### ISSUE TITLE
Wrong field in index.html

### ISSUE THREAD

**Issue by BerniPi** [weatherstorm/Sofaskin-CW9009#9]
One field in the "one year ago"-Card in index.html is wrong.
The wind row is " <td>$days_ago($days_ago=$n).wind.max $day.wind.gustdir</td>". So $days_ago ist missing for the direction.

**Comment by weatherstorm** [comment]
Thanks for sharing this. I have found a few other errors like this as well. I will be sending an update soon.

**Comment by weatherstorm** [comment]
Fixed. New version will be out soon. Thanks.
